export const domains = {
    "abnamroctvm.b3bee.com.br": "ABN AMRO CLEARING CTVM",
    "acqio.com.br": "Acqio",
    "bs2.com": "Adiq",
    "adyen.com": "Adyen",
    "desenvolve.mt.gov.br": "AF ESTADO DE MT-DESENVOLVE MT",
    "fomentoservicos.pr.gov.br": "AF PARANÁ",
    "age.pe.gov.br": "AG FOMENTO EST PERNAMBUCO S.A.",
    "goiasfomento.com": "AGENCIA FOMENTO GOIAS",
    "ailos.coop.br": "AILOS",
    "al5bank.com.br": "AL5 S.A. - Crédito Financiamento e Investimento",
    "alelo.com.br": "Alelo",
    "alesta.com.br": "ALESTA SCD S.A.",
    "amazon.com": "Amazon",
    "amedigital.com": "AME DIGITAL BRASIL IP LTDA.",
    "americanexpress.com": "Amex",
    "asaas.com": "ASAAS IP S.A.",
    "aticca.com.br": "ATICCA SCD S.A.",
    "ativainvestimentos.com.br": "ATIVA INVESTIMENTOS S.A. CTCV",
    "avancard.com.br": "Avancard",
    "azimutbrasil.com.br": "AZIMUT BRASIL DISTRIBUIDORA DE",
    "bancoazumi.com.br": "AZUMI DTVM",
    "abcbrasil.com.br": "Banco ABC Brasil S.A.",
    "abnamro.b3bee.com.br": "BANCO ABN AMRO CLEARING S.A.",
    "afinz.com.br": "Banco Afinz S.A. Banco Múltiplo",
    "agibank.com.br": "Banco Agibank S.A.",
    "bancoalfa.com.br": "Banco Alfa S.A.",
    "andbank-lla.com.br": "Banco Andbank (Brasil) S.A.",
    "andbank.com": "Banco ANDBANK (Brasil) S.A.",
    "bancoarbi.com.br": "BANCO ARBI S.A.",
    "b3.com.br": "BANCO B3 S.A.",
    "https://bancob3.com.br/": "Banco B3 S.A.",
    "bancobari.com.br": "Banco Bari S. A.",
    "bancobmg.com.br": "BANCO BMG S.A.",
    "bnpparibas.com.br": "Banco BNP Paribas Brasil S.A.",
    "ib.bnpparibas.com.br": "Banco BNP Paribas Brasil S.A.",
    "bocombbm.com.br": "BANCO BOCOM BBM S.A.",
    "bancobbm.com.br": "Banco BOCOM BBM S.A.",
    "ibi.com.br": "Banco Bradescard S.A.",
    "bradesco.com": "BANCO BRADESCO S.A.",
    "bradesco.com.br": "Banco Bradesco S.A.",
    "bancobbcdigital.com.br": "Banco Brasileiro de Crédito S.A.",
    "bancobs2.com.br": "BANCO BS2 S.A.",
    "bs2.com/banco/": "Banco BS2 S.A.",
    "btgpactual.com": "Banco BTG Pactual S.A.",
    "c6consig.com.br/": "Banco C6 Consignado S.A.",
    "c6bank.com.br": "BANCO C6 S.A.",
    "c6bank.com/": "Banco C6 S.A.",
    "bcgbrasil.com.br": "Banco Caixa Geral - Brasil S.A.",
    "bancocargill.com.br": "Banco Cargill S.A.",
    "bancocedula.com.br": "Banco Cedula S.A.",
    "cetelem.com.brpt": "Banco Cetelem",
    "bancocifra.com.br": "Banco Cifra S.A.",
    "corporateportal.brazil.citibank.com": "BANCO CITIBANK S.A.",
    "citibank.com.br": "Banco Citibank S.A.",
    "cnhindustrialcapital.com": "Banco CNH Industrial Capital S.A.",
    "travelexbank.com.br": "BANCO CONFIDENCE DE CAMBIO S.A.",
    "bancoob.com.br": "Banco Cooperativo do Brasil S.A. - BANCOOB",
    "Sicoob.com.br": "Banco Cooperativo Sicoob S.A.",
    "sicredi.com.br": "Banco Cooperativo Sicredi S.A.",
    "calyon.com.br": "Banco Credit Agricole Brasil S.A.",
    "ca-cib.com.br": "Banco Credit Agricole Brasil S.A.",
    "csfb.com": "Banco Credit Suisse (Brasil) S.A.",
    "cshg.com.br": "Banco Credit Suisse (Brasil) S.A.",
    "carrefoursolucoes.com.br": "BANCO CSF S.A.",
    "bancoamazonia.com.br": "Banco da Amazônia S.A.",
    "bankofchina.b3bee.com.br": "BANCO DA CHINA BRASIL S.A.",
    "boc-brazil.com": "Banco da China Brasil S.A.",
    "bankofchina.com": "Banco da China Brasil S.A.",
    "daycoval.com.br": "BANCO DAYCOVAL S.A.",
    "bandes.b3bee.com.br": "BANCO DE DESENV ES SA",
    "bdmg.mg.gov.br": "Banco de Desenvolvimento de Minas Gerais S.A. BDMG",
    "bandes.com.br": "Banco de Desenvolvimento do Espírito Santo S.A. – BANDES",
    "dllgroup.com": "Banco de Lage Landen Brasil S.A.",
    "bancodigimais.com.br": "BANCO DIGIMAIS S.A.",
    "bancodigimais.com.br/": "Banco Digimais S.A.",
    "aebb.com.br": "Banco Digio S.A.",
    "digio.com.br": "Banco Digio S.A.",
    "bb.com.br": "Banco do Brasil S.A.",
    "banese.com.br": "Banco do Estado de Sergipe S.A.",
    "banpara.b.br": "Banco do Estado do Pará S.A.",
    "banpara.br": "Banco do Estado do Pará S.A.",
    "banrisul.com.br": "Banco do Estado do Rio Grande do Sul S.A.",
    "bnb.gov.br": "Banco do Nordeste",
    "banconordeste.gov.br": "Banco do Nordeste do Brasil S.A.",
    "banese.b.br": "BANCO EST.DE SERGIPE",
    "fator.com.brbanco": "Banco Fator S.A.",
    "bancofibra.com.br": "BANCO FIBRA S.A.",
    "bancofidis.com.br": "Banco Fidis S.A.",
    "bancofinaxis.com.br": "Banco Finaxis S.A.",
    "finaxis.com.br": "Banco Finaxis S.A.",
    "bancogenial.com": "Banco Genial S.A.",
    "chevroletsf.com.br": "Banco GM S.A.",
    "bancoguanabara.com.br": "Banco Guanabara S.A.",
    "bancohonda.com.br": "BANCO HONDA S.A.",
    "ibm.com/financing/br": "Banco IBM S.A.",
    "inbursa.com.br": "BANCO INBURSA",
    "bancoinbursa.com": "Banco Inbursa S.A.",
    "bancoinbursa.com.br": "Banco Inbursa S.A.",
    "bancoinduscred.com.br": "BANCO INDUSCRED DE INVESTIMENTO",
    "bancoindustrial.com.br": "Banco Industrial do Brasil S.A.",
    "bib.com.br": "Banco Industrial do Brasil S.A.",
    "bip.b.br": "BANCO INDUSVAL S/A",
    "bancointer.com.br": "Banco Inter S.A.",
    "intermedium.com.br": "Banco Intermedium S.A.",
    "itaubba.com.br": "Banco Itaú BBA S.A.",
    "bancofiat.com.br": "Banco Itaú VeÃ­culos S.A.",
    "itaubank.com.br": "Banco ItauBank S.A",
    "jpmorgan.com": "Banco J. P. Morgan S.A.",
    "safra.com.br": "Banco J. Safra S.A",
    "jpmorgan.com.br": "BANCO J.P. MORGAN S.A",
    "deere.com.br": "BANCO JOHN DEERE S.",
    "johndeere.com.br": "Banco John Deere S.A.",
    "bancokomatsu.com.br": "BANCO KOMATSU S.A.",
    "letsbank.com.br": "Banco Letsbank S.A.",
    "lusobrasileiro.com.br": "Banco Luso Brasileiro S.A.",
    "bancoluso.com.br": "Banco Luso Brasileiro S.A.",
    "bancomaster.com.br": "Banco Master S.A.",
    "mercantil.com.br": "Banco Mercantil do Brasil S.A.",
    "mercantildobrasil.com.br": "Banco Mercantil do Brasil S.A.",
    "bancomercedes-benz.com.br": "BANCO MERCEDES BENZ DO BRASIL SA",
    "mizuhobank.com/brazil/pt/": "Banco Mizuho do Brasil S.A.",
    "mizuhobank.com": "Banco Mizuho do Brasil S.A.",
    "bancomodal.com.br": "Banco Modal S.A.",
    "modal.com.br": "Banco Modal S.A.",
    "bancomoneo.com.br": "BANCO MONEO S.A.",
    "br.bk.mufg.jp": "BANCO MUFG BRASIL S.A.",
    "bndes.gov.br": "BANCO NAC DES ECON E SOCIAL",
    "banconacional.com.br": "Banco Nacional",
    "bancooriginal.com.br": "Banco Original",
    "original.com.br": "Banco Original S.A.",
    "bancopan.com.br": "Banco PAN S.A.",
    "bancopaulista.com.br": "Banco Paulista S.A.",
    "pine.com": "Banco Pine S.A.",
    "rabobank.com.br": "Banco Rabobank International Brasil S.A.",
    "bancorandon.com": "BANCO RANDON S.A.",
    "bancorenault.com.br": "Banco RCI Brasil S.A.",
    "rendimento.com.br": "BANCO RENDIMENTO S.A.",
    "brp.com.br": "Banco Ribeirao Preto S.A.",
    "bancornx.com.br": "BANCO RNX S.A.",
    "rodobens.com.br": "BANCO RODOBENS S.A",
    "santander.com.br": "Banco Santander  (Brasil)  S.A.",
    "bancosemear.com.br": "Banco Semear S.A.",
    "senff.com.br/": "Banco Senff S.A.",
    "senff.com.br": "Banco Senff S.A.",
    "societegeneralebrasil.com.br": "BANCO SOCIETE GENERAL",
    "sgbrasil.com.br": "Banco Société Générale Brasil S.A.",
    "sofisa.com.br": "Banco Sofisa S.A.",
    "pilar3fidis.integraltrust.com.br": "BANCO STELLANTIS S.A.",
    "smbcgroup.com.br": "BANCO SUMITOMO MITSUI BRASILEIRO",
    "bancotopazio.com.br": "BANCO TOPÁZIO S.A.",
    "bancotoyota.com.br": "BANCO TOYOTA DO BRASIL S.A.",
    "tribanco.com.br": "BANCO TRIANGULO S.A.",
    "tricury.com.br": "Banco Tricury S.A",
    "voiter.com": "Banco Voiter S.A.",
    "bip.b.brvoiter": "Banco Voiter S.A.",
    "bancovw.com.br": "Banco Volkswagen S.A.",
    "bancovotorantim.com.br": "Banco Votorantim S.A.",
    "bv.com.br": "Banco Votorantim S.A.",
    "vrinvestimentos.com.br": "Banco VR S.A.",
    "bancovr.com.br": "Banco VR S.A.",
    "bancowesternunion.com.br": "Banco Western Union do Brasil S.A.",
    "pilar3.wooribank.com.br": "BANCO WOORI BANK DO BRASIL S.A.",
    "wooribank.com.br": "Banco Woori Bank do Brasil S.A.",
    "yamaha-motor.com.br": "Banco Yamaha Motor do Brasil S.A.",
    "yamahaservicosfinanceiros.com.br": "BANCO YAMAHA MOTOR S.A.",
    "bancokebhana.com.br": "BANCO. KEB HANA DO BRASIL S.A.",
    "bancoseguro.com.br": "BancoSeguro S.A.",
    "banesecard.com.br": "Banese Card",
    "banestes.com.br": "BANESTES S.A. Banco do Estado do Espírito Santo",
    "bofabrazil.com.br": "BANK OF AMERICA MERRILL LYNCH",
    "bankofamerica.com.mx": "Bank Of America Merrill Lynch Banco Multiplo S.A.",
    "ml.com": "Bank of America Merrill Lynch Banco Múltiplo S.A.",
    "banparanet.com.br": "Banpará",
    "barucred.com.br": "BARU SCD S.A.",
    "bancobcv.com.br": "BCV - Banco de Crédito e Varejo S.A.",
    "pilar3bexs.integraltrust.com.br": "BEXS BANCO. DE CAMBIO S.A.",
    "moneyp.com.br": "BMP Sociedade de Crédito Direto S.A.",
    "bmw.com.br": "BMW FINANCEIRA S.A. - CFI",
    "boltcard.com.br": "Bolt Card",
    "bonuspago.com.br": "BONUSPAGO SCD S.A.",
    "brap.com.br": "BR Partners Banco de Investimento S.A.",
    "bradescard.com.br": "BradesCard",
    "bankpar.com.br": "Bradesco Cartões",
    "msbank.com.br": "Braza Bank S.A. Banco de Câmbio",
    "brb.com.br": "BRB - Banco de Brasília",
    "novo.brb.com.br": "BRB BANCO DE BRASILIA",
    "cartaobrb.com.br": "BRBcard",
    "brcardcrediario.com": "BRCARD SCD S.A.",
    "bvfinanceira.com.br": "BV Financeira",
    "c6bank.com": "C6 Bank",
    "caixa.gov.br": "Caixa Econômica Federal",
    "calcred.com.br": "CALCRED S.A.",
    "caroldtvm.com.br": "CAROL DTVM LTDA.",
    "cartos.com.br": "Cartos Sociedade de Crédito Direto S.A.",
    "caruanafinanceira.com.br": "Caruana S.A. - Soc. de Créd Financ. e Invest.",
    "casadocredito.com.br": "CASA CREDITO S.A. SCM",
    "cashme.com.br": "CashMe",
    "cateno.com.br": "Cateno",
    "wscredcooperinfor.facilinformatica.com.br": "CCCE TRAB EMP TEC INF BH CID L",
    "credicoamo.com.br": "CCR CREDICOAMO CREDITO RURAL C",
    "celcoin.com.br": "Celcoin Instituição de Pagamento S.A.",
    "caprate.com.br": "CF GROUP",
    "br.ccb.com": "China Construction Bank (Brasil) Banco Mult. S.A.",
    "cielo.com.br": "Cielo",
    "citibank.com": "Citibank N.A.",
    "cobansa.com": "Cobansa S.A.",
    "conexioncambio.com.br": "CONEXION CORR. DE CAMBIO LTDA.",
    "cresol.coop.br": "Conf. Nac. Coop. Cen. Créd. Econ. Fam. Sol. Cresol",
    "confidencecambio.com.br": "CONFIDENCE CC S.A.",
    "credicoopavel.com.br": "Cooperativa de Credito Rural Coopavel",
    "crediseara.com.br": "Cooperativa de Crédito Rural Seara - Crediseara",
    "corporeinvest.com.br": "CORPORE SCD S.A.",
    "credialianca.com.br": "Credialiança Cooperativa de Crédito Rural",
    "crediare.com.br": "CREDIARE S.A. - CFI",
    "credisan.com.br": "CREDISAN",
    "credisis.com.br": "Credisis Central de Cooperativas de Crédito Ltda",
    "creditas.com": "CREDITAS SCD",
    "credsystem.com.br": "Credsystem",
    "credz.com.br": "Credz",
    "csileasing.com.br": "CSILATINA A.M. S.A.",
    "csu.com.br": "CSU",
    "bcb.tanger.com.br": "DAUX SCD",
    "delcred.com.br": "Delcred Sociedade de Crédito Direto S.A.",
    "desenbahia.ba.gov.br": "DESENBAHIA - AG.FOM",
    "desenvolvesp.com.br": "Desenvolve SP-Agência de Fomento do Estado de São Paulo",
    "deutsche-bank.com.br": "Deutsche Bank S.A. - Banco Alemão",
    "deutsche-leasing.com": "DEUTSCHE SPARKASSEN LEASING DO",
    "vocedmfinanceira.com.br": "DM Financeira S.A. - Crédito Financiamento e Investimento",
    "vocedm.com.brportal": "DM Sociedade de Crédito Direto S.A.",
    "dock.tech": "Dock - Credenciadora",
    "ebanx.combr": "Ebanx",
    "bexs.com.br": "Ebury Banco de Câmbio S.A.",
    "economisa.com.br": "ECONOMISA CIA HIPOTECARIA",
    "ticket.com.br": "Edenred",
    "sejaefi.com.br": "Efí S.A. – Instituição de Pagamento",
    "cartaoelo.com.br": "Elo",
    "emgea.gov.br": "EMGEA - Empresa Gestora de Ativos",
    "entrepay.com.br": "Entrepay",
    "factafinanceira.com.br": "Facta Financeira S.A. Crédito Financiamento e Inv",
    "finamax.com.br": "FINAMAX S.A. CFI",
    "finvestdtvm.com.br": "FINVEST DTVM",
    "firstdata.com.ar": "fiserv.",
    "fontecred.com.br": "FONTECRED SCD S/A",
    "areacliente.fortbrasil.com.br": "FORTBRASIL IP S/A",
    "gazinbank.com.br": "GAZINCRED S.A. SCFI",
    "gazincred.com.br": "GazinCred S.A. Sociedade de Crédito Financiamento e Investimento",
    "gertec.com.br": "Gertec",
    "giro.tech": "GIRO - SCD S/A",
    "goldmansachs.com": "GOLDMAN SACHS DO BRASIL BM S.A",
    "granitopagamentos.com.br": "Granito",
    "green.com.ai": "GREEN ALTERNATIVE INVESTMENTS",
    "haitongib.com.br": "HAITONG BANCO DE INVESTIMENTO",
    "hinova.com.br": "HINOVA PAY IP S.A.",
    "hipercard.com.br": "Hipercard Banco Múltiplo S.A.",
    "pilar3hp.integraltrust.com.br": "HP FINANCIAL SERV.ARR.MER.S.A.",
    "hrdigitalscd.com.br": "HR DIGITAL SCD",
    "hsfinanceira.com.br": "HS FINANCEIRA S.A CFI",
    "hubfintech.com.br": "Hub Fintech",
    "icbc.b3bee.com.br": "ICBC DO BRASIL BM S.A.",
    "idsf.com.br": "ID Corretora de Títulos e Valores Mobiliários S.A.",
    "ingenico.com.br": "Ingenico",
    "pilar3integralaccess.integraltrust.com.br": "INTEGRAL ACCESS DTVM",
    "intesasanpaolobrasil.com.br": "INTESA SANPAOLO BRASIL S.A-BM",
    "itau.com.br": "ITAU UNIBANCO S.A.",
    "iugu.com": "Iugu Instituição de Pagamento S.A.",
    "jpmorganchase.com": "JPMorgan Chase Bank National Association",
    "lar.ind.br": "Lar Cooperativa de Crédito - Lar Credi",
    "levycam.com.br": "LEVYCAM C.C.V. LTDA",
    "liminedtvm.com.br": "LIMINE TRUST DTVM LTDA.",
    "soulisto.com.br": "Listo",
    "bancoxyz.com.br": "LISTO SCD S.A.",
    "pontoslivelo.com.br": "Livelo",
    "atendimento.magnumbank.com.br": "MAGNUM SCD",
    "mastercard.combr": "Mastercard",
    "mercadopago.com.br": "Mercadopago.com Representações Ltda.",
    "midway.com.br": "Midway S. A. Crédito Financiamento e Investimento",
    "bacen.bancomidway.com.br": "MIDWAY S.A. - SCFI",
    "monbank.net": "MONETARIE SCD",
    "bancomoneycorp.com.br": "Moneycorp Banco de Câmbio S.A.",
    "somosmooz.com": "Mooz",
    "mundinvest.com.br": "MUNDINVEST S.A. - CCVM",
    "biorcfinanceira.com.br": "NEON FINANCEIRA - CFI S.A.",
    "neon.com.br": "Neon Financeira – Sociedade de Crédito Financiamento e Investimento S.A.",
    "newlandnpt.com.br": "Newland",
    "nbcbank.com.br": "NOVO BANCO CONTINENTAL S.A.-BM",
    "nubank.com.br": "NUBANK",
    "omni.com.br": "Omni S.A. Crédito Financiamento e Investimento",
    "oncred.com.br": "ONCRED - SCD S.A.",
    "otimoscd.app.br": "ÓTIMO SCD S.A.",
    "ourinvest.com.br": "OURIBANK S.A.",
    "chphipotecaria.com.br": "Oxy Companhia Hipotecária",
    "pag.ai": "Pag.aí",
    "pagseguro.uol.com.br": "PagSeguro - Credenciadora",
    "pagueveloz.com.br": "Pagueveloz",
    "paranabanco.com.br": "Paraná Banco S.A.",
    "parati-cfi.com.br": "Parati Crédito Financiamento e Investimento S.A.",
    "paynet.net.br": "Paynet",
    "paypal.combr": "Paypal",
    "picchioni.com.br": "PBM-PICCHIONI-BELGO-M.DTVM S/A",
    "picpay.com": "Picpay Bank – Banco Múltiplo S.A.",
    "lecca.com.br": "PICPAY INVEST",
    "pismo.io": "Pismo",
    "sodexobeneficios.com.br": "Pluxee",
    "portoseguro.com.br": "Porto Seguro",
    "positivo.com.br": "Positivo",
    "poupex.com.br": "Poupex",
    "qitech.com.br": "QI Sociedade de Crédito Direto S.A.",
    "souqista.com.br": "Qista (FC Financeira S.A – Crédito Financiamento e Investimento)",
    "souqista.b3bee.com.br": "QISTA S.A. CFI",
    "bancoreag.com.br": "REAG TRUST DTVM",
    "realizesolucoesfinanceiras.com.br": "REALIZE CFI S.A.",
    "recargapay.com.br": "Recargapay",
    "redscd.com.br": "RED SCD S.A.",
    "redecard.com.br": "Rede",
    "dtvm.com.br": "RENASCENCA DTVM LTDA",
    "safrapay.com.br": "Safrapay",
    "abecip.org.br": "Santa Luzia Empreendimentos Imobiliários",
    "santinvest.com.br": "SANTINVEST S.A. - CFI",
    "zebracambio.com.br": "SAYGO CÂMBIO",
    "sbcash.com.br": "SBCASH SCD",
    "scaniabanco.com.br": "Scania Banco S.A.",
    "kredilig.com.br": "SCFI KREDILIG S.A",
    "br.scotiabank.com": "SCOTIABANK BRASIL S.A.",
    "senff-bacen.s3.sa-east-1.amazonaws.com": "SENFFNET IP LTDA.",
    "sf3.com.br": "SF3 CRéDITO FINANCIAMENTO E I",
    "simpala.com.br": "SIMPALA S.A. CFI",
    "simplificpavarini.com.br": "SIMPLIFIC PAVARINI",
    "sinosserrafinanceira.com.br": "SINOSSERRA S/A - SCFI",
    "sisprimedobrasil.com.br": "SISPRIME DO BRASIL – COOPERATIVA DE CRÉDITO",
    "socinal.com.br": "SOCINAL S.A. - CRED FIN INVEST",
    "socredsa.com.br": "SOCRED SA - SCMEPP",
    "starafinanceira.com.br": "STARA FINANCEIRA S.A. - CFI",
    "starcred.com": "STARCRED SCD S.A.",
    "starkbank.com": "Stark Bank S.A. - Instituição de Pagamento",
    "starkbank.combr": "Stark Sociedade de Crédito Direto S.A.",
    "statestreet.com": "STATE STREET BR S.A. BANCO COMER",
    "pilar3stellantis.integraltrust.com.br": "STELLANTIS FINANCIAMENTOS CFI",
    "stone.com.br": "Stone Instituição de Pagamento S.A.",
    "stripe.com": "Stripe",
    "sumup.com.br": "Sumup",
    "tectoy.com.br": "Tec Toy",
    "bot.tentoscap.com.br": "TENTOS S.A. CFI",
    "bancoconfidence.com.br": "Travelex Banco de Câmbio S.A.",
    "tullettprebon.com.br": "TULLETT PREBON BRASIL CVC LTDA",
    "ubs.com": "UBS Brasil Banco de Investimento S.A.",
    "unicred.com.br": "UNICRED DO BRASIL",
    "valecard.com.br": "Valecard",
    "verifone.com.br": "Verifone",
    "visa.com.br": "Visa",
    "services.westernasset.com": "WESTERN ASSET DTVM LTDA.",
    "willbank.com.br": "WILL BANK",
    "willfinanceira.com.br": "Will Financeira S.A. - Crédito Financiamento e Investimento",
    "worldpay.com": "Worldpay",
    "xpi.com.br": "XP Investimentos S.A.",
    "pilar3zema.integraltrust.com.br": "ZEMA CFI S/A",
    "zemafinanceira.com": "Zema Crédito Financiamento e Investimento S. A."
  }